name: build-devices

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-ios:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-11, macos-10.15]
        steps:
            -   uses: actions/checkout@v2
            -   name: build 
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "CRC"  -destination "generic/platform=ios"
                    xcrun xcodebuild build -scheme "SHA2" -destination "generic/platform=ios"
    build-tvos:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-11, macos-10.15]
        steps:
            -   uses: actions/checkout@v2
            -   name: build 
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "CRC"  -destination "generic/platform=tvos"
                    xcrun xcodebuild build -scheme "SHA2" -destination "generic/platform=tvos"
    build-watchos:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-11, macos-10.15]
        steps:
            -   uses: actions/checkout@v2
            -   name: build 
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "CRC"  -destination "generic/platform=watchos"
                    xcrun xcodebuild build -scheme "SHA2" -destination "generic/platform=watchos"
